apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jawwad78/eks-gitops
    targetRevision: HEAD
    path: terraform/modules/kubernetes/app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    