apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-letsencrypt
  namespace: cert-manager
  
spec:
  secretName: cert-letsencrypt-secret # where your certificate will be stored once retrieved from let's encrypt
  dnsNames:
    - app.jawwad.org
    - grafana.jawwad.org
    - argocd.jawwad.org

  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    