apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: cert-manager
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.port.port }}
      targetPort: {{ .Values.port.targetPort }}
      