
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.port.port }}
      targetPort: {{ .Values.port.targetPort }}
      