app:
  name: jawwad-app

service:
  name: jawwad-service

port:
  port: 80
  containerPort: 80
  targetPort: 80

container:
  image: "726661503364.dkr.ecr.eu-west-2.amazonaws.com/eks:ca15274a5ca9ae58bdad5c856ac32ca3b569f26c" #change this to your image in ecr
