app:
  name: jawwad-app

service:
  name: jawwad-service

port:
  port: 80
  containerPort: 80
  targetPort: 80

container:
  image: "726661503364.dkr.ecr.eu-west-2.amazonaws.com/eks:ae9c0563330287a4343bd3b77c11933dd83a17f1" #change this to your image in ecr
