name: build image and codedeploy
on:
  push:
    branches: ['main']
    paths: 
      - app/**

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/eks
  IMAGE_TAG: ${{ github.sha }} #build docker image with  same commit sha

permissions:
  id-token: write #  it asks github to make the oidc token
  contents: read  #allows this pipeline to read files in this github repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
      - name: checks out code
        uses: actions/checkout@v4
    
      - name: get aws creds
        uses: aws-actions/configure-aws-credentials@v3
        with :
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/eksoidc  
          aws-region: ${{ env.AWS_REGION }}  
        
      - name: Build image
        id: build-image 
        run: |
         docker build -f ./app/Dockerfile -t $AWS_ECR_REPO:$IMAGE_TAG ./app  
         echo "image=$AWS_ECR_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ steps.build-image.outputs.image }}
          format: 'table'
          exit-code: 0
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true #if there are no updated patches of the version, it will ignore it 
          version: 'v0.69.2'
        
      - name: login to ecr
        uses: aws-actions/amazon-ecr-login@v2  
      - name: push image
        id: push-image    
        run:
         docker push ${{ steps.build-image.outputs.image }}