name: Terraform destroy
on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write #  it allows github to make the oidc token
  contents: read  #allows this pipeline to read files in this github repo

jobs: 
 terraform-destroy:
   name: Terraform destroy-auto-approve
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: ./terraform

   
   steps:
     - name: checks out code
       uses: actions/checkout@v4
     - name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v3
       with : 
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/eksoidc 
          aws-region: ${{ env.AWS_REGION }}
          
     - name: give executable permission to bash script
       run: chmod +x  bash-script/delete.sh

     - name: delete traefik svc
       run:  bash-script/delete.sh

     - name: Hashicorp - Terraform setup
       uses: hashicorp/setup-terraform@v3.1.2      

     - name: Terraform Init
       run: terraform init
    
     - name: use tfavrs from secrets
       run: |
         cat <<'STOP' > terraform.tfvars
         ${{ secrets.TFVARS_SECRET }}
         STOP
                
     - name: Terraform destroy
       run: terraform destroy -auto-approve